name: hk
on:
  workflow_dispatch:
    inputs:
      triggle:
        description: 'triggle'
  schedule:
     - cron:  '0 02,04,06,08,10,12,14,16,18,20,22 * * *' # 每2个小时触发一次
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: pip install opencv-python requests 
      - name: Run mytvhk
        run: python ${{ github.workspace }}/hk.py
        - name: Run getip
        run: python ${{ github.workspace }}/spiders.py
     
      - name: Commit results
        run: |
          git config --local user.email "wuzhij@mail.com"
          git config --local user.name "wzsvip"
          if [ -n "$(git status --porcelain)" ]; then
            git add *.txt *.m3u
            git commit -m "Automatic update"
            #git pull --rebase
            git push -f
